networks:
  scooty-web:
    driver: bridge
services:
  api:
    build:
      context: ./repositories/backend
      dockerfile: Dockerfile
    container_name: api
    depends_on:
    - db
    env_file: .env
    links:
    - db:db
    networks:
    - scooty-web
    ports:
    - 8000:8000
    restart: always
  bike_hivemind:
    build:
      context: ./repositories/bike
      dockerfile: Dockerfile
    container_name: bike_hivemind
    depends_on:
    - db
    - api
    env_file: .env
    networks:
    - scooty-web
    ports:
    - 8001:8001
    restart: unless-stopped
  db:
    container_name: database-db-1
    env_file: .env
    image: postgis/postgis
    networks:
    - scooty-web
    ports:
    - 5432:5432
    restart: always
  webclient-prod:
    build:
      context: ./repositories/frontend
      dockerfile: ./dockerfiles/prod/Dockerfile
    container_name: scooty-web-prod
    env_file: .env
    depends_on:
    - api
    networks:
    - scooty-web
    ports:
    - 3000:3000
    restart: unless-stopped

  adminer:
     image: adminer
     networks:
       - scooty-web
     container_name: database-adminer-1
     restart: always
     depends_on:
       - db
     ports:
       - "8080:8080"
