services:
  simulation:
    build:
      context: ./simulation
      dockerfile: Dockerfile
    container_name: simulation_app
    depends_on:
    - bike_hivemind
    - api
    - db
    env_file: .env
    networks:
    - scooty-web
    restart: 'no'
    volumes:
    - ./simulation/src:/app/simulation/src
    - ./src:/app/src