networks:
  scooty-web:
    driver: bridge
services:
  api:
    build:
      context: ./repositories/backend
      dockerfile: Dockerfile
    container_name: api
    depends_on:
    - db
    environment:
      BIKE_URL: http://bike_hivemind:8001/
      DATABASE_URL: postgresql+asyncpg://user:pass@db:5432/sddb
      DEBUG: 'false'
      ENVIRONMENT: local
      GITHUB_CLIENT_ID: secretid
      GITHUB_CLIENT_SECRET: secresecret
      GITHUB_REDIRECT_URI: http://secret.secret/
      PROJECT_NAME: scooty-doo
      USE_MOCKED_BIKE_CALL: 'false'
    links:
    - db:db
    networks:
    - scooty-web
    ports:
    - 8000:8000
    restart: always
  bike_hivemind:
    build:
      context: ./repositories/bike
      dockerfile: Dockerfile
    container_name: bike_hivemind
    depends_on:
    - db
    - api
    environment:
      BACKEND_URL: http://api:8000/
      DEFAULT_SPEED: 20000
      TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMCIsInNjb3BlcyI6WyJhZG1pbiJdfQ.ARAUHRnbeLFiTxpg9_xv5iPWtaA-u_o9GXHRwx3zlGs'
      INIT_BIKES_REMOTELY: "true"
      BIKE_LIMIT: 9999
    networks:
    - scooty-web
    ports:
    - 8001:8001
    restart: unless-stopped
  db:
    container_name: database-db-1
    environment:
      POSTGRES_DB: sddb
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    image: postgis/postgis
    networks:
    - scooty-web
    ports:
    - 5432:5432
    restart: always
    volumes:
    - pgdata:/var/lib/postgresql/data
  webclient-prod:
    build:
      context: ./repositories/frontend
      dockerfile: ./dockerfiles/prod/Dockerfile
    container_name: scooty-web-prod
    depends_on:
    - api
    networks:
    - scooty-web
    ports:
    - 3000:3000
    restart: unless-stopped
volumes:
  pgdata: null
